Repository michael-gokey-architect/bio-ui-pages, pull requests merged in 2024-05, with the labels that each got.

#3 Step 14- Added Angular Material basic ~ try2
  README.md
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/guest-profile/guest-profile.component.html
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/index.html
  src/styles.css
  tailwind.config.js
Labels: enhancement

#7 added theme switcher and moved some builts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/built/a01c4-guest-web-links/a01c4-guest-web-links.component.css
  src/app/built/a01c4-guest-web-links/a01c4-guest-web-links.component.html
  src/app/built/a01c4-guest-web-links/a01c4-guest-web-links.component.spec.ts
  src/app/built/a01c4-guest-web-links/a01c4-guest-web-links.component.ts
  src/app/built/a05b-guest-public-landing/a05b-guest-public-landing.component.css
  src/app/built/a05b-guest-public-landing/a05b-guest-public-landing.component.html
  src/app/built/a05b-guest-public-landing/a05b-guest-public-landing.component.spec.ts
  src/app/built/a05b-guest-public-landing/a05b-guest-public-landing.component.ts
  src/app/header/header.component.html
  src/app/theme-switcher/theme-switcher.component.css
  src/app/theme-switcher/theme-switcher.component.html
  src/app/theme-switcher/theme-switcher.component.spec.ts
  src/app/theme-switcher/theme-switcher.component.ts
Labels: enhancement

#8 Robyne's Dailies
  README.md
  angular.json
  package-lock.json
  src/app/a01a-guest-sign-in/a01a-guest-sign-in.component.html
  src/app/a01a-guest-sign-up/a01a-guest-sign-up.component.html
  src/app/a01b-guest-welcome-back/a01b-guest-welcome-back.component.html
  src/app/a01b-guest-welcome/a01b-guest-welcome.component.html
  src/app/a01c3-guest-social-media/a01c3-guest-social-media.component.html
  src/app/a01d1-guest-home/a01d1-guest-home.component.html
  src/app/a01d2-guest-display/a01d2-guest-display.component.html
  src/app/b04a-vendor-bio-about/b04a-vendor-bio-about.component.html
  src/app/b04b-vendor-bio-landing-display/b04b-vendor-bio-landing-display.component.html
  src/app/b04c-vendor-media-build/b04c-vendor-media-build.component.html
  src/app/b04d-vendor-media-display/b04d-vendor-media-display.component.html
  src/app/b04e-vendor-shop-display/b04e-vendor-shop-display.component.html
  src/assets/images/design-photos/a01a-guest-sign-in.png
  src/assets/images/design-photos/a01a-guest-sign-up.png
  src/assets/images/design-photos/a01b-guest-welcome .png
  src/assets/images/design-photos/a01b-guest-welcome-back .png
  src/assets/images/design-photos/a01c2-guest-about      .png
  src/assets/images/design-photos/a01c3-guest-social-media.png
  src/assets/images/design-photos/a01c4-guest-web-links.png
  src/assets/images/design-photos/a02a-update-your-password.png
  src/assets/images/design-photos/a02a2-update-your-password.png
  src/assets/images/design-photos/a02a3-update-your-password.png
  src/assets/images/design-photos/a04a-hamburger-nav.png
  src/assets/images/design-photos/a04a2-ham-nav-manage-account.png
  src/assets/images/design-photos/a04a3-ham-nav-manage-alias.png
  src/assets/images/design-photos/a05a-guest-profile-landing.png
  src/assets/images/design-photos/a05b-guest-public-landing.png
  src/assets/images/design-photos/a05c-event-landing.png
  src/assets/images/design-photos/b04a-vendor-about-landing-display.png
  src/assets/images/design-photos/b04b-vendor-bio-landing-display.png
  src/assets/images/design-photos/b04c-vendor-about .png
  src/assets/images/design-photos/b04d-vendor-Media-kit -display.png
  src/assets/images/design-photos/b04e-vendor-shop-display .png
Labels: help wanted

#9 daily updates
  src/app/a05b-guest-taking-qr/a05b-guest-taking-qr.component.css
  src/app/a05b-guest-taking-qr/a05b-guest-taking-qr.component.html
  src/app/a05b-guest-taking-qr/a05b-guest-taking-qr.component.spec.ts
  src/app/a05b-guest-taking-qr/a05b-guest-taking-qr.component.ts
  src/app/a05c-guest-connection-indicator/a05c-guest-connection-indicator.component.css
  src/app/a05c-guest-connection-indicator/a05c-guest-connection-indicator.component.html
  src/app/a05c-guest-connection-indicator/a05c-guest-connection-indicator.component.spec.ts
  src/app/a05c-guest-connection-indicator/a05c-guest-connection-indicator.component.ts
  src/app/a06a-guest-connecions-landing/a06a-guest-connecions-landing.component.css
  src/app/a06a-guest-connecions-landing/a06a-guest-connecions-landing.component.html
  src/app/a06a-guest-connecions-landing/a06a-guest-connecions-landing.component.spec.ts
  src/app/a06a-guest-connecions-landing/a06a-guest-connecions-landing.component.ts
  src/app/a06c-guest-requests-landing/a06c-guest-requests-landing.component.css
  src/app/a06c-guest-requests-landing/a06c-guest-requests-landing.component.html
  src/app/a06c-guest-requests-landing/a06c-guest-requests-landing.component.spec.ts
  src/app/a06c-guest-requests-landing/a06c-guest-requests-landing.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/built/a01a-guest-sign-in/a01a-guest-sign-in.component.css
  src/app/built/a01a-guest-sign-in/a01a-guest-sign-in.component.html
  src/app/built/a01a-guest-sign-in/a01a-guest-sign-in.component.spec.ts
  src/app/built/a01a-guest-sign-in/a01a-guest-sign-in.component.ts
  src/app/built/a01a-guest-sign-up/a01a-guest-sign-up.component.css
  src/app/built/a01a-guest-sign-up/a01a-guest-sign-up.component.html
  src/app/built/a01a-guest-sign-up/a01a-guest-sign-up.component.spec.ts
  src/app/built/a01a-guest-sign-up/a01a-guest-sign-up.component.ts
  src/app/built/a01b-guest-welcome/a01b-guest-welcome.component.css
  src/app/built/a01b-guest-welcome/a01b-guest-welcome.component.html
  src/app/built/a01b-guest-welcome/a01b-guest-welcome.component.spec.ts
  src/app/built/a01b-guest-welcome/a01b-guest-welcome.component.ts
  src/app/built/a01c3-guest-social-media/a01c3-guest-social-media.component.css
  src/app/built/a01c3-guest-social-media/a01c3-guest-social-media.component.html
  src/app/built/a01c3-guest-social-media/a01c3-guest-social-media.component.spec.ts
  src/app/built/a01c3-guest-social-media/a01c3-guest-social-media.component.ts
  src/app/sitemap/sitemap.component.html
  src/app/sitemap/sitemap.component.spec.ts
  src/app/sitemap/sitemap.component.ts
Labels: enhancement

#12 S2b rp
  README.md
  src/app/d09a-quest-badges/d09a-quest-badges.component.html
  src/app/d09b-quest-stats/d09b-quest-stats.component.html
  src/app/d09c-quest-qr/d09c-quest-qr.component.html
  src/app/d09d-quest-rewards/d09d-quest-rewards.component.html
  src/app/d09e-quests-redeemed/d09e-quests-redeemed.component.html
  src/app/e08a-event-home/e08a-event-home.component.html
  src/assets/images/design-photos/01a-guest-sign-in.jpg
  src/assets/images/design-photos/01a-guest-sign-up.jpg
  src/assets/images/design-photos/01b-guest-welcome-back.jpg
  src/assets/images/design-photos/01b-guest-welcome.jpg
  src/assets/images/design-photos/01c3-guest-social-media.jpg
  src/assets/images/design-photos/01c4-guest-web-links.jpg
  src/assets/images/design-photos/01d1-guest-home.jpg
  src/assets/images/design-photos/01d2-guest-display.jpg
  src/assets/images/design-photos/04-vendor-bio-about.jpg
  src/assets/images/design-photos/04-vendor-media-build.jpg
  src/assets/images/design-photos/04-vendor-media-display.jpg
  src/assets/images/design-photos/04-vendor-shop-display.jpg
  src/assets/images/design-photos/04-vendor-store-connect-codes.jpg
  src/assets/images/design-photos/04-vendor-store-connect.jpg
  src/assets/images/design-photos/08-event-home.jpg
  src/assets/images/design-photos/08-event-schedule.jpg
  src/assets/images/design-photos/09-quest-badges.jpg
  src/assets/images/design-photos/09-quest-qr.jpg
  src/assets/images/design-photos/09-quest-rewards.jpg
  src/assets/images/design-photos/09-quest-stats.jpg
  src/assets/images/design-photos/09-quests-redeemed.jpg
  src/assets/images/design-photos/a05b-guest-taking-qr.png
  src/assets/images/design-photos/a05c-guest-connection-indicator.png
  src/assets/images/design-photos/a06a-guest-connecions-landing.png
  src/assets/images/design-photos/a06a1-guest-connecions-landing-swipe-left.png
  src/assets/images/design-photos/a06a2-guest-connecions-landing-swipe-right.png
  src/assets/images/design-photos/a06a3-guest-connecions-landing-scroll.png
  src/assets/images/design-photos/a06b-guest-connecions-landing-search.png
  src/assets/images/design-photos/a06c-guest-requests-landing.png
  src/assets/images/design-photos/a06c1-guest-requests-landing-swipe-left.png
  src/assets/images/design-photos/a06c2-guest-requests-landing-swipe-right.png
  src/assets/images/design-photos/c05c-event-landing.png
  src/assets/images/design-photos/d09a-quest-badges.png
  src/assets/images/design-photos/d09b-quest-stats.png
  src/assets/images/design-photos/d09d-quest-rewards.png
  src/assets/images/design-photos/temporary-badge-images/1x/badge1-blue.png
  src/assets/images/design-photos/temporary-badge-images/1x/badge1-gray.png
  src/assets/images/design-photos/temporary-badge-images/1x/badge2-gray.png
  src/assets/images/design-photos/temporary-badge-images/1x/badge2-purple.png
  src/assets/images/design-photos/temporary-badge-images/1x/badge3-gray.png
  src/assets/images/design-photos/temporary-badge-images/1x/badge3-pink.png
Labels: help wanted

#10 Added welcome, password update, manage account, and guest landing pages
  src/app/a01b-guest-welcome-back/a01b-guest-welcome-back.component.html
  src/app/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.css
  src/app/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.html
  src/app/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.spec.ts
  src/app/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.css
  src/app/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.html
  src/app/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.spec.ts
  src/app/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.ts
  src/app/b04e-vendor-shop-display/b04e-vendor-shop-display.component.html
  src/app/built/a02a-update-your-password/a02a-update-your-password.component.html
  src/app/built/a05b-guest-public-landing/a05b-guest-public-landing.component.html
  src/app/d09a-quest-badges/d09a-quest-badges.component.html
  src/app/d09b-quest-stats/d09b-quest-stats.component.html
  src/app/d09d-quest-rewards/d09d-quest-rewards.component.html
  src/app/guest-connection-indicator/guest-connection-indicator.component.css
  src/app/guest-connection-indicator/guest-connection-indicator.component.html
  src/app/guest-connection-indicator/guest-connection-indicator.component.spec.ts
  src/app/guest-connection-indicator/guest-connection-indicator.component.ts
  src/app/guest-taking-qr/guest-taking-qr.component.css
  src/app/guest-taking-qr/guest-taking-qr.component.html
  src/app/guest-taking-qr/guest-taking-qr.component.spec.ts
  src/app/guest-taking-qr/guest-taking-qr.component.ts
Labels: needs help

#14 Day One Sprint 3 WIP, Robyne loads, stubs built, pages built
  README.md
  src/app/a05b-guest-taking-qr/a05b-guest-taking-qr.component.html
  src/app/a05c-guest-connection-indicator/a05c-guest-connection-indicator.component.html
  src/app/a06a-guest-connecions-landing/a06a-guest-connecions-landing.component.html
  src/app/a06c-guest-requests-landing/a06c-guest-requests-landing.component.html
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/b04d-vendor-media-display/b04d-vendor-media-display.component.html
  src/app/b04d-vendor-media-display/b04d-vendor-media-display.component.spec.ts
  src/app/b04d-vendor-media-display/b04d-vendor-media-display.component.ts
  src/app/built/a01b-guest-welcome-back/a01b-guest-welcome-back.component.css
  src/app/built/a01b-guest-welcome-back/a01b-guest-welcome-back.component.html
  src/app/built/a01b-guest-welcome-back/a01b-guest-welcome-back.component.spec.ts
  src/app/built/a01b-guest-welcome-back/a01b-guest-welcome-back.component.ts
  src/app/built/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.css
  src/app/built/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.html
  src/app/built/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.spec.ts
  src/app/built/a04a2-ham-nav-manage-account/a04a2-ham-nav-manage-account.component.ts
  src/app/built/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.css
  src/app/built/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.html
  src/app/built/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.spec.ts
  src/app/built/b04d-vendor-media-kit-display/b04d-vendor-media-kit-display.component.ts
  src/app/built/b04e-vendor-shop-display/b04e-vendor-shop-display.component.css
  src/app/built/b04e-vendor-shop-display/b04e-vendor-shop-display.component.html
  src/app/built/b04e-vendor-shop-display/b04e-vendor-shop-display.component.spec.ts
  src/app/built/b04e-vendor-shop-display/b04e-vendor-shop-display.component.ts
  src/app/built/d09a-quest-badges/d09a-quest-badges.component.css
  src/app/built/d09a-quest-badges/d09a-quest-badges.component.html
  src/app/built/d09a-quest-badges/d09a-quest-badges.component.spec.ts
  src/app/built/d09a-quest-badges/d09a-quest-badges.component.ts
  src/app/built/d09b-quest-stats/d09b-quest-stats.component.css
  src/app/built/d09b-quest-stats/d09b-quest-stats.component.html
  src/app/built/d09b-quest-stats/d09b-quest-stats.component.spec.ts
  src/app/built/d09b-quest-stats/d09b-quest-stats.component.ts
  src/app/built/d09d-quest-rewards/d09d-quest-rewards.component.css
  src/app/built/d09d-quest-rewards/d09d-quest-rewards.component.html
  src/app/built/d09d-quest-rewards/d09d-quest-rewards.component.spec.ts
  src/app/built/d09d-quest-rewards/d09d-quest-rewards.component.ts
  src/app/c05c-event-landing/c05c-event-landing.component.css
  src/app/c05c-event-landing/c05c-event-landing.component.html
  src/app/c05c-event-landing/c05c-event-landing.component.spec.ts
  src/app/c05c-event-landing/c05c-event-landing.component.ts
  src/app/e08b-event-schedule/e08b-event-schedule.component.html
  src/app/guest-connection-indicator/guest-connection-indicator.component.css
  src/app/guest-connection-indicator/guest-connection-indicator.component.html
  src/app/guest-connection-indicator/guest-connection-indicator.component.spec.ts
  src/app/guest-connection-indicator/guest-connection-indicator.component.ts
  src/app/guest-taking-qr/guest-taking-qr.component.css
  src/app/guest-taking-qr/guest-taking-qr.component.html
  src/app/guest-taking-qr/guest-taking-qr.component.spec.ts
  src/app/guest-taking-qr/guest-taking-qr.component.ts
  src/assets/images/design-photos/a01c2-guest-about.png
  src/assets/images/design-photos/b04d-vendor-Media-kit-display.png
  src/assets/images/design-photos/b04e-vendor-shop-display.png
Labels: enhancement

#18 Temp Fix Error - Comment Out Missing Files
  src/app/app-routing.module.ts
  src/app/app.module.ts
Labels: bug

#20 html updates and images upload
  src/app/e08b-event-schedule/e08b-event-schedule.component.html
  src/app/page-not-found/page-not-found.component.html
  src/assets/images/design-photos/a03a-404-Error.jpg
  src/assets/images/design-photos/d08B-quest-qr-scan.png
  src/assets/images/design-photos/d08a-quest-new-interaction.png
  src/assets/images/design-photos/d08c-quest-collected.png
  src/assets/images/design-photos/d09a2-quest-badges.png
  src/assets/images/design-photos/theme-switcher/TS-DragonCon.png
  src/assets/images/design-photos/theme-switcher/TS-NYIAS.png
  src/assets/images/design-photos/theme-switcher/TS-PatchWRQ.png
  src/assets/images/design-photos/theme-switcher/TS-grays.png
Labels: documentation

#31 tweaked landing page and made footer
  src/app/footer/footer.component.html
  src/app/index-landing/index-landing.component.html
  src/app/theme-switcher/theme-switcher.component.html
  src/assets/images/onboarding-images/Facebook.png
  src/assets/images/onboarding-images/Instagram.tif.png
  src/assets/images/onboarding-images/JohnBianchi.png
  src/assets/images/onboarding-images/Linkedin.tif.png
  src/assets/images/onboarding-images/PatchwrqBg.png
  src/assets/images/onboarding-images/X.tif.png
  src/styles.css
Labels: good first issue
